FROM nodered/node-red:3.1.0-14

#FROM nodered/node-red:2.0.6
RUN npm install node-red-contrib-stackhero-influxdb-v2 node-red-contrib-ui-led  node-red-dashboard node-red-contrib-ui-thermostat node-red-node-random  node-red-contrib-influxdb node-red-node-snmp
 