---
http-url: "https://horizon:8980/opennms"
id: "minion-02"
location: "minion2-location"

karaf:
  shell:
    ssh:
      host: "0.0.0.0"

ipc:
  grpc:
    host: "nginx"
    port: "443"

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
